### ISSUE TITLE
Temporary file is not deleted on Windows.

### ISSUE THREAD

**Issue by s1as3r** [s1as3r/GoSpotDl#1]
The temporary file that is downloaded and the later converted by ffmpeg is not deleted in windows.

Actual Error:
```
 The process cannot access the file because it is being used by another process.
```

**Comment by s1as3r** [comment]
A lame but straightforward solution would be to just `time.Sleep()` but I think there would be a better solution.

**Comment by GGP1** [comment]
You are trying to delete a file that is currently opened and this throws an error on windows machines.

```go
fileName := strings.Join(artistNames, ", ") + " - " + s.Name
file, err := os.Create(fileName + ".temp")
if err != nil {
	return err
}
defer file.Close() // Deferred funcs are executed on return

...

_, err = io.Copy(io.MultiWriter(file, bar), resp.Body)
if err != nil {
	return err
}
// You could close the file here as it isn't used anymore -> file.Close()

if err := os.Remove(fileName + ".temp"); err != nil {
	return fmt.Errorf("Error removing temp file(%s.temp): %s", fileName, err)
}

return nil
```

I would also suggest using

```go
filename :=  fmt.Sprintf("%s - %s", strings.Join(artistNames, ", "),  s.Name)
tempFile := filename + ".temp"
mp3File := filename + ".mp3"
```

instead of 

```go
fileName := strings.Join(artistNames, ", ") + " - " + s.Name
// and then repeating multiple times
fileName + ".temp"
fileName + ".mp3"
```

Edit: the standard library has a os.CreateTemp to create a temporary file in case that's what you are looking for, it returns the file and then you just need to use file.Name()

**Comment by s1as3r** [comment]
> You are trying to delete a file that is currently opened and this throws an error on windows machines.
>
> `defer file.Close() // Deffered funcs are executed on return`

Ah, an obvious thing that my inexperienced eye couldn't spot.
Thank You for your help.
